import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import topics from "./api/topics";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to DevLaka Learning</h1>

          <p className={styles.description}>
            Get started Learning
            <code className={styles.code}>learn/code</code>
          </p>

          <div className={styles.grid}>
            {topics.map((topic) => {
              const { id } = topic;
              return (
                <Link key={id} href={`/learn/${id}`}>
                  <a className={styles.card}>
                    <h2>Learn {topic.id} &rarr;</h2>
                    <p>{topic.description}</p>
                  </a>
                </Link>
              );
            })}
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </Layout>
    </div>
  );
}
